// Generated by typings
// Source: https://raw.githubusercontent.com/kineticfaction/DefinitelyTyped/cf5ad00c6f3bb2a293cd4e96523e9f76972e12c1/express-busboy/express-busboy.d.ts
// Type definitions for express-busboy
// Project: https://www.npmjs.org/package/express-busboy
// Definitions by: Oliver Ridgway <https://github.com/kineticfaction/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare namespace Express {

  export interface Request {
    files?: any;
    sessionID
  }

}

declare module "express-busboy" {
  
  import * as core from "express-serve-static-core";
  
  export function extend(one: core.Express, two: any): void;
  
}
